[versions]
# plugins
flatpak-generator = "1.5.0"
replace-placeholders = "3.0"

# libraries
classgraph = "4.8.184"
jakarta-websocket = "2.2.0"
javagi = "0.12.2"
jetbrains-annotations = "26.0.2-1"
junit = "6.0.0"
junit-platform = "6.0.0"
lombok = "1.18.42"
stormyaml = "1.0.1"
yajl = "2.1.0"
yajsi = "3.0.1"

[libraries]
# annotations / lombok
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# toxicstoxm
yajl = { group = "com.toxicstoxm.YAJL", name = "YAJL", version.ref = "yajl" }
yajsi = { group = "com.toxicstoxm", name = "YAJSI", version.ref = "yajsi" }
stormyaml = { group = "com.toxicstoxm", name = "StormYAML", version.ref = "stormyaml" }

# runtime libs
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }
javagi-adw = { group = "io.github.jwharm.javagi", name = "adw", version.ref = "javagi" }

jakarta-websocket-client = { group = "jakarta.websocket", name = "jakarta.websocket-client-api", version.ref = "jakarta-websocket" }
tyrus-client = { group = "org.glassfish.tyrus", name = "tyrus-client", version.ref = "jakarta-websocket" }
tyrus-grizzly-client = { group = "org.glassfish.tyrus", name = "tyrus-container-grizzly-client", version.ref = "jakarta-websocket" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
flatpak-generator = { id = "io.github.jwharm.flatpak-gradle-generator", version.ref = "flatpak-generator" }
replace-placeholders = { id = "io.github.crimix.replace-placeholders", version.ref = "replace-placeholders" }
